config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :parents
  resources :children
  resources :educators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboards#index'
  get 'dashboard/nines', to: 'dashboards#child'
  get 'dashboard/educadoras', to: 'dashboards#educator'
  root 'home#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
    enum type_profile: [:director, :educadora, :nine, :apoderado]
    enum sex: [:masculino, :femenino, :otro]
    has_one :parent, dependent: :destroy
    has_one :child, dependent: :destroy
    has_one :educator, dependent: :destroy
    belongs_to :user, optional: true
    has_one_attached :avatar
    accepts_nested_attributes_for :child
    accepts_nested_attributes_for :educator

    scope :child_request, -> { where(:type_profile => 2)}
    
    scope :educator_request, -> { where(:type_profile => 1)}

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: [:new, :create]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
        format.js {}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
        format.js {}
        mail(@profile.id, @profile.updated_at)
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(
        :rut, :names, :last_names, :date_of_birth, :nationality, :sex, :address, :phone, :type_profile, :avatar, 
        child_attributes:[:id_fundation, :grade, :phone_secure, :entry, :egress, :profile_id],
        educator_attributes:[:type_educator, :profile_id])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut %>
  </div>

  <div class="field">
    <%= form.label :names %>
    <%= form.text_field :names %>
  </div>

  <div class="field">
    <%= form.label :last_names %>
    <%= form.text_field :last_names %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.number_field :sex %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :type_profile %>
    <%= form.number_field :type_profile %>
  </div>

  <div class="field"> 
    <%= form.label 'avatar' %>
    <%= form.file_field :avatar%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/edit.js.erb
$('#modal_edit').empty();
$('#modal_edit').html(`
                <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edicion de Tarea</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <%= form_with(model: @profile, method: :patch, remote: true) do |form| %>
                            <div class="field">
                                <%= form.label :names %>
                                <%= form.text_field :names %>
                            </div>

                            <div class="field">
                                <%= form.label :last_names %>
                                <%= form.text_field :last_names %>
                            </div>

                            <div class="field">
                                <%= form.label :date_of_birth %>
                                <%= form.date_select :date_of_birth %>
                            </div>

                            <div class="field">
                                <%= form.label :nationality %>
                                <%= form.text_field :nationality %>
                            </div>

                            <div class="field">
                                <%= form.label :sex %>
                                <%= form.select :sex, Profile.sexes.keys.to_a %>
                            </div>

                            <div class="field">
                                <%= form.label :address %>
                                <%= form.text_field :address %>
                            </div>

                            <div class="field">
                                <%= form.label :phone %>
                                <%= form.text_field :phone %>
                            </div>
                            <div class="field"> 
                                <%= form.label 'avatar' %>
                                <%= form.file_field :avatar%>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                <%= form.submit "edit", class: "btn btn-primary", id: "edit"%>
                            </div>
                            <% end %>
                    </div>
                </div>
                </div>`);

$('#myModal').modal()

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>Names</th>
      <th>Last names</th>
      <th>Date of birth</th>
      <th>Nationality</th>
      <th>Sex</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Type profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.rut %></td>
        <td><%= profile.names %></td>
        <td><%= profile.last_names %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= profile.nationality %></td>
        <td><%= profile.sex %></td>
        <td><%= profile.address %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.type_profile %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%= render './dashboards/navbar' %>
<div id="jumbotron_show" class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4 text-light">Nuestra Señora de la Victoria</h1>
        <p class="lead text-light">Bienvenido a tu perfil</p>
    </div>
</div>
<p id="notice"><%= notice %></p>
<div id="profile" class="container">
  <div class="row">
    <div class="col-sm-4"><%= image_tag(@profile.avatar.variant(resize: '350x350').processed, alt: 'imagen con problemas') if @profile.avatar.attached? %></div>
    <div class="col-sm-8">

      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Rut: </strong><%= @profile.rut %></li>
        <li class="list-group-item"><strong>Nombre: </strong><%= @profile.names %> <%= @profile.last_names %></li>
        <li class="list-group-item"><strong>Fecha de nacimiento:</strong><%= @profile.date_of_birth %></li>
        <li class="list-group-item"><strong>Nacionalidad: </strong><%= @profile.nationality %></li>
        <li class="list-group-item"><strong>Sexo: </strong><%= @profile.sex %></li>
        <li class="list-group-item"><strong>Direccion: </strong><%= @profile.address %></li>
        <li class="list-group-item"><strong>Telefono: </strong><%= @profile.phone %></li>
        <% if @profile.type_profile == 'educadora' %>
          <li class="list-group-item"><strong>Cargo: </strong><%= @profile.educator.type_educator %></li>
        <% end %>
        <% if @profile.type_profile == 'nine' %>
          <li class="list-group-item"><strong>Id fundacion: </strong><%= @profile.child.id_fundation %></li>
          <li class="list-group-item"><strong>Nivel: </strong><%= @profile.child.grade %></li>
          <li class="list-group-item"><strong>Telefono de seguridad: </strong><%= @profile.child.phone_secure %></li>
          <li class="list-group-item"><strong>Año de Entrada: </strong><%= @profile.child.entry %></li>
          <li class="list-group-item"><strong>Año de Egreso: </strong><%= @profile.child.egress %></li>
        <% end %>
        <li class="list-group-item"><%= link_to 'Edit', edit_profile_path(@profile), remote: true %></li>
      </ul>
    </div>
  </div>
</div>
<div id="modal_edit">
</div>
<%= render './dashboards/footer' %>

app/views/profiles/update.js.erb
$('#profile').empty();

$('#profile').html(`
                        <div class="row">
                            <div class="col-sm-4"><%= image_tag(@profile.avatar.variant(resize: '350x350').processed, alt: 'imagen con problemas') if @profile.avatar.attached? %></div>
                            <div class="col-sm-8">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><strong>Rut: </strong><%= @profile.rut %></li>
                                <li class="list-group-item"><strong>Nombre: </strong><%= @profile.names %> <%= @profile.last_names %></li>
                                <li class="list-group-item"><strong>Fecha de nacimiento:</strong><%= @profile.date_of_birth %></li>
                                <li class="list-group-item"><strong>Nacionalidad: </strong><%= @profile.nationality %></li>
                                <li class="list-group-item"><strong>Sexo: </strong><%= @profile.sex %></li>
                                <li class="list-group-item"><strong>Direccion: </strong><%= @profile.address %></li>
                                <li class="list-group-item"><strong>Telefono: </strong><%= @profile.phone %></li>
                                <li class="list-group-item"><strong>Tipo de perfil:</strong><%= @profile.type_profile %></li>
                                <% if @profile.educator %>
                                <li class="list-group-item"><strong>Cargo: </strong><%= @profile.educator.type_educator %></li>
                                <% end %>
                                <li class="list-group-item"><%= link_to 'Edit', edit_profile_path(@profile), remote: true %></li>
                            </ul>
                            </div>
                        </div>
                        `);

$('#modal_edit').empty()
$('.modal-backdrop').remove()