config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :parents
  resources :children
  resources :educators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboards#index'
  get 'dashboard/nines', to: 'dashboards#child'
  get 'dashboard/educadoras', to: 'dashboards#educator'
  root 'home#index'
end

app/models/educator.rb
class Educator < ApplicationRecord
  enum type_educator: [:parvularia, :tecnico_parvularia, :practicante, :otros]
  belongs_to :profile
end

app/controllers/educators_controller.rb
class EducatorsController < ApplicationController
  before_action :set_educator, only: %i[ show edit update destroy ]

  # GET /educators or /educators.json
  def index
    if(params[:q])
      @educators = Profile.educator_request.where('names LIKE ? OR last_names LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
    else
      @educators = Profile.educator_request
    end
  end

  # GET /educators/1 or /educators/1.json
  def show
  end

  # GET /educators/new
  def new
    @profile = Profile.new
    @profile.build_educator
  end

  # GET /educators/1/edit
  def edit
  end

  # POST /educators or /educators.json
  def create
    @educator = Educator.new(educator_params)

    respond_to do |format|
      if @educator.save
        format.html { redirect_to @educator, notice: "Educator was successfully created." }
        format.json { render :show, status: :created, location: @educator }
        format.js {}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @educator.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /educators/1 or /educators/1.json
  def update
    respond_to do |format|
      if @educator.update(educator_params)
        format.html { redirect_to @educator, notice: "Educator was successfully updated." }
        format.json { render :show, status: :ok, location: @educator }
        format.js {}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @educator.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /educators/1 or /educators/1.json
  def destroy
    @educator.destroy
    respond_to do |format|
      format.html { redirect_to educators_url, notice: "Educator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_educator
      @educator = Educator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def educator_params
      params.require(:educator).permit(:type_educator, :profile_id)
    end
end

app/helpers/educators_helper.rb
module EducatorsHelper
end

app/views/educators/_form.html.erb
<%= form_with(model: educator, local: true) do |form| %>
  <% if educator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(educator.errors.count, "error") %> prohibited this educator from being saved:</h2>

      <ul>
      <% educator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_educator %>
    <%= form.number_field :type_educator %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/educators/_new.html.erb
<h1>New Educator</h1>

<%= render 'form', educator: @educator %>

<%= link_to 'Back', educators_path %>

app/views/educators/create.js.erb
$('#card_educators').append(`
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                            <%= image_tag(educator.avatar.variant(resize: '190x200').processed, alt: 'imagen con problemas') if educator.avatar.attached? %>
                            </div>
                            <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">Nombre: <%= educator.names %> <%= educator.last_names %></h5><hr>
                                <p class="card-text">RUT: <%= educator.rut %></p><hr>
                                <p class="card-text">Fecha de nacimiento: <%= educator.date_of_birth %></p><hr>
                                <button type="button" class="btn btn-primary"><%= link_to 'Ver mas', educator, remote: true %></button>
                            </div>
                            </div>
                        </div>
                    </div> 
                    `);

$('#modal_new').empty()
$('.modal-backdrop').remove()

app/views/educators/edit.html.erb
<h1>Editing Educator</h1>

<%= render 'form', educator: @educator %>

<%= link_to 'Show', @educator %> |
<%= link_to 'Back', educators_path %>

app/views/educators/index.html.erb
<%= render './dashboards/navbar' %>
<div id="jumbotron_educators" class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4 text-light">Nuestras Educadoras</h1>
        <br><br><br>
    </div>
</div>
<div class='container'>
<p id="notice"><%= notice %></p>
        <div class="row">
        <div class="col">
            <%= link_to "<button>Nueva Educadora</button>".html_safe, new_educator_path, remote: true  %>
        </div>
        <div class="col">
            <%= form_with(url: educators_path, method: :get, remote: true) do |form| %>
                <%= form.text_field :q %>
                <%= form.submit 'Buscar por nombre o apellido' %>
            <% end %>
        </div>  
        </div>

<hr>

    <div id='card_educators'>
        <% @educators.each do |educator|%>
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <%= image_tag(educator.avatar.variant(resize: '190x200').processed, alt: 'imagen con problemas') if educator.avatar.attached? %>
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Nombre: <%= educator.names %> <%= educator.last_names %></h5><hr>
                            <p class="card-text">RUT: <%= educator.rut %></p><hr>
                            <p class="card-text">Fecha de nacimiento: <%= educator.date_of_birth %></p><hr>
                            <%= link_to "<button>Mas información</button>".html_safe, educator %>
                        </div>
                        </div>
                    </div>
                </div>
        <% end%>

    </div>

</div>

<div id="modal_new">
</div>

<%= render './dashboards/footer' %>

app/views/educators/index.js.erb
$('#card_educators').empty()

<% @educators.each do |educator|%>
    $('#card_educators').append(`
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <%= image_tag(educator.avatar.variant(resize: '190x200').processed, alt: 'imagen con problemas') if educator.avatar.attached? %>
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Nombre: <%= educator.names %> <%= educator.last_names %></h5><hr>
                            <p class="card-text">RUT: <%= educator.rut %></p><hr>
                            <p class="card-text">Fecha de nacimiento: <%= educator.date_of_birth %></p><hr>
                            <%= link_to "<button>Mas información</button>".html_safe, educator, remote: true %>
                        </div>
                        </div>
                    </div>
                </div>   
                `)
<% end%>

app/views/educators/new.html.erb
<h1>New Educator</h1>

<%= render 'form', educator: @educator %>

<%= link_to 'Back', educators_path %>

app/views/educators/new.js.erb
$('#modal_new').empty();
$('#modal_new').html(`
                <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Crear un nuevo niñe</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <%= form_with(model: @profile, method: :new, local: true) do |form| %>
                        <div class="field">
                            <%= form.label 'Rut' %>
                            <%= form.text_field :rut %>
                        </div>
                        
                        <div class="field">
                            <%= form.label 'Nombres' %>
                            <%= form.text_field :names %>
                        </div>

                        <div class="field">
                            <%= form.label 'Apellidos' %>
                            <%= form.text_field :last_names %>
                        </div>

                        <div class="field">
                            <%= form.label 'Fecha de nacimiento' %>
                            <%= form.date_select :date_of_birth %>
                        </div>

                        <div class="field">
                            <%= form.label 'Nacionalidad' %>
                            <%= form.text_field :nationality %>
                        </div>

                        <div class="field">
                            <%= form.label 'Sexo' %>
                            <%= form.select :sex, Profile.sexes.keys.to_a %>

                        </div>

                        <div class="field">
                            <%= form.label 'Direccion' %>
                            <%= form.text_field :address %>
                        </div>

                        <div class="field">
                            <%= form.label 'Telefono' %>
                            <%= form.text_field :phone %>
                        </div>
                            <%= form.hidden_field :type_profile, :value => 'educadora' %>

                        <%= form.fields_for :educator do |formf| %>
                            <div class="field">
                                <%= formf.label :type_educator %>
                                <%= formf.select :type_educator, Educator.type_educators.keys.to_a %>
                            </div>
                            
                        <% end %>   
                        <div class="field"> 
                            <%= form.label 'avatar' %>
                            <%= form.file_field :avatar%>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            <%= form.submit "crear", class: "btn btn-primary", id: "new"%>
                        </div>
                    <% end %>
                </div>
            </div>
           </div>
                `);

$('#myModal').modal()

app/views/educators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type educator:</strong>
  <%= @educator.type_educator %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @educator.profile %>
</p>

<%= link_to 'Edit', edit_educator_path(@educator) %> |
<%= link_to 'Back', educators_path %>