config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  resources :parents
  resources :children
  resources :educators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboards#index'
  get 'dashboard/nines', to: 'dashboards#child'
  get 'dashboard/educadoras', to: 'dashboards#educator'
  root 'home#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @user = User.find(current_user.id)
        @pie_sex = Profile.child_request.group(:sex).count
        @bar_type_educator = Educator.group(:type_educator).count
    end
end

app/views/dashboards/_footer.html.erb
<footer class="mt-auto py-3">
    <div class='container'>
        <%= image_tag('LOGO_NSDLV.png', size: '70x70') %>
            <div>
                
            </div>
    </div>
</footer>

app/views/dashboards/_navbar.html.erb
<nav style="background-color:#6155a6;"> 
    <div class='container'  >

        <div class="row align-items-center">
            <div class="col-2">
                <%= image_tag('LOGO_NSDLV.png', size: '70x70') %>
            </div>
            <div class="col-8">
                <%= link_to "Inicio", dashboard_path, style: 'color:#ffe6e6;' %>
                <%= link_to 'Mi Perfil', profile_path(current_user.profile.id), style: 'color:#ffe6e6;' %>
                <%= link_to "Niñes", children_path, style: 'color:#ffe6e6;' %>
                <% if current_user.profile.type_profile == 'director' %>
                    <%= link_to "Educadoras", educators_path, style: 'color:#ffe6e6;' %>
                <% end %>
            </div>
            <div class="col-2 navbar-collapse">
                <%= link_to  raw('<i class="fas fa-sign-out-alt fa-3x" style="color:#ffe6e6;"></i>'), destroy_user_session_path, method: :delete %>
            </div>
        </div>
    </div>
</nav>

app/views/dashboards/index.html.erb
<%= render 'navbar' %>
<%# jumbotron %>
    <div id="jumbotron_index" class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4 text-light">Nuestra Señora de la Victoria</h1>
            <p class="lead text-light">Bienvenid@ <%= @user.profile.names %> <%= @user.profile.last_names %></p>
        </div>
    </div>
    <div class='container'>
        <div class='row'>
            <%# Profiles %>
            <div class='col-sm-6 m-3 border rounded'>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Nombre: <%= @user.profile.names %> <%= @user.profile.last_names %></li>
                        <li class="list-group-item">Rut: <%= @user.profile.rut %></li>
                        <li class="list-group-item">Nacionalidad: <%= @user.profile.nationality %></li>
                        <li class="list-group-item">Sexo: <%= @user.profile.sex %></li>
                        <li class="list-group-item">Fecha de nacimiento: <%= @user.profile.date_of_birth %></li>
                        <li class="list-group-item">Direccion: <%= @user.profile.address %></li>
                        <li class="list-group-item">Telefono: <%= @user.profile.phone %></li>
                    </ul>
            </div>
            <%# Bhirtdays %>
            <div class='col-sm-5 m-3 border rounded'>
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://i.ibb.co/mRwXN0g/Whats-App-Image-2021-04-13-at-18-12-12.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="https://i.ibb.co/DLFs6VP/Whats-App-Image-2021-04-13-at-17-54-23.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="https://i.ibb.co/Mpy2cXL/Whats-App-Image-2021-04-13-at-18-12-12-1.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="https://i.ibb.co/372XFJr/Whats-App-Image-2021-04-13-at-18-12-12-2.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="https://i.ibb.co/Lzn8V7N/Whats-App-Image-2021-04-13-at-18-12-12-3.jpg" class="d-block w-100" alt="...">
                    </div>
                </div>
                </div>
            </div>
        </div>
        <%# Graphics %>
        <div class='row'>
            <div class='col-sm-5 m-3 border rounded'>
            <%= column_chart @bar_type_educator, title: "Tipos de Educadoras" %>
            </div>
            <div class='col-sm-5 m-3 border rounded'>
            <%= pie_chart @pie_sex, title: "Cantidad de niñes por sexo"%>
            </div>
        </div>
    </div>
<%= render 'footer' %>